#!/usr/bin/env bash

# -- Add service to runlevel.

rc-update add nvidia-suspend async
rc-update add nvidia-resume async
rc-update add nvidia-hibernate async
rc-update add nvidia-powerd async

# -- Update services list.

rc-update -u
